### ISSUE TITLE
Need to mix Http.Error and Graphql.Http.Error when using tasks

### ISSUE THREAD

**Issue by johnhydroware** [dillonkearns/elm-graphql#118]
I need to mix http requests and graphql requests in a task chain mixing Task.onError and Task.andThen.

One use case is that the graphql request may fail with a 401 and then I need to make a HTTP request to refresh my token and then redo the request. All other errors, both from HTTP and GraphQL needs to be part of the final Tasks error case. Therefore I need to wrap Http.Error in Graphql.Http.Error.

For now I have solved it after a http task with ```|> Task.onError (\e -> Task.fail (mapToGraphqlError e))```
and manually implemented my own mapper from ```Http.Error``` to ```Graphql.Http.Error```

**Comment by dillonkearns** [comment]
Hello! Yes, this is a bit awkward, I wish the `elm/http` package used an Http.Error type that included that extra information.

I believe this problem is addressed with this helper function: https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/Graphql-Http#withSimpleHttpError. I'll close this issue, but feel free to re-open if there's anything else to discuss. Thank you!
