### ISSUE TITLE
Nested optional arguments constructors

### ISSUE THREAD

**Issue by Maxim-Filimonov** [dillonkearns/elm-graphql#124]
Hey,
I have been playing with a GraphQL API which has nested optional arguments. While it's not a problem with plain string GraphQL query, it's really cumbersome to make it work with existing generated code.
The GQL query:
```graphql
    {
    team_updates(where: {team_name: {_eq: "123"}}) {
        video_url
        }
    }
```
[Schema](https://cobra-reify.herokuapp.com/v1alpha1/graphql)

Our resulting query in elm-graphql:
```elm
equalToTeam: String -> OptionalArgument Text_comparison_exp
equalToTeam teamName = Present <| buildText_comparison_exp (\args -> { args | eq_ = Present teamName })

whereTeamName: String -> OptionalArgument Team_updates_bool_exp
whereTeamName teamName = Present <| buildTeam_updates_bool_exp (\args -> {args | team_name = equalToTeam teamName})

getUpdates : String -> SelectionSet TeamUpdateResponse RootQuery
getUpdates teamName =
    team_updates (\args -> {args | where_ = whereTeamName teamName}) CobraGQL.Object.Team_updates.video_url
```
What I would like to write instead is something like:
```elm
getUpdates teamName = 
    team_updates (\args -> {args | where_ = (\whereArgs -> { whereArgs | team_name = (\teamNameArgs -> {teamNameArgs | {eq_ = Present teamName}})})}) CobraGQL.Object.Team_updates.video_url
```
I can try to help with PR to generator, want to get some feedback the design first. Would there be an actual reason where an optional nested argument need to have passed an actual object instead of function?
To avoid breaking existing code which relies on it being an object, maybe a separate name like 
whereWithOptionals would be better?

**Comment by dillonkearns** [comment]
Hey Maxim,

Thanks for starting the discussion. Optional Arguments to me is definitely one of elm's few pain points. I wish there was a first-class syntax that made it easier to express optional arguments in a type-safe yet lightweight way.

That said, to me when I see code that has a large number of optional input arguments, that's a code smell to me. Essentially it's exposing a client-side ORM to access the database in a low-level way. So the solution here from my perspective would be to create some high-level ways to access this. I believe you're using Hasura. So you should be able to create a Postgres function here to abstract this away if I'm not mistaken.

Ideally, I would create a function that allows you to have a query like:

```graphql
  {
    # if this query always requires a team_name, let's make it a required argument
    # and let's avoid exposing other optional arguments that we don't 
    # end up needing on the client side (instead of exposing an ORM
    # for doing every possible kind of query)
    teamUpdatesByName(team_name: "123") {
        video_url
        }
    }
```

Regardless of the code-generation, the more high-level the GraphQL endpoint is, the better your experience with `elm-graphql` will be (just naturally because of the way that elm is). I also consider this to be a good practice in general. I'm of the opinion that a GraphQL API works best when it is a high-level expression of what is *meaningful* in the domain (that is, the GraphQL Schema models the small subset of correct and meaningful ways to access/change data, not every possibility).


So unless there's a clear use case that makes a compelling argument for exploring something like this, I'd like to avoid adding additional complexity (both in the generated code, and in additional magic for users to learn about).

**Comment by Maxim-Filimonov** [comment]
Thanks for reply @dillonkearns.
I understand your reasoning. Though, I do feel that creating custom functions for the sake of generated code is a bit strange. 
In normal GraphQL query:
```
    {
    team_updates(where: {team_name: {_eq: "123"}}) {
        video_url
        }
    }
```
Extra function might work well for a scenario where we are queuing by equality, what happens if I want to query by inclusion? I'd need to create another function which would allow me to do that. Practically, defeating the whole purpose of having GraphQL and working on SQL level instead.
To me this code:
```
buildTeam_updates_bool_exp (\args -> {args | team_name = equalToTeam teamName})
```
introduces more complexity as I need to dig through generated code to find the exact internal type to use here.
While for root level optional types we do this instead
```
team_updates (\args -> {args | where_ = whereTeamName teamName}) 
```
The user already needs to learn how to work with those optionals anyway. 
My point being is inconsistent handling of optional values depending on their depth.

**Comment by dillonkearns** [comment]
> I understand your reasoning. Though, I do feel that creating custom functions for the sake of generated code is a bit strange.

To me, it doesn't seem like that's something for the sake of the generated code. It seems like having a high-level GraphQL API which exposes clear interfaces to exactly what you would like to expose (hiding low-level details from the database, and preventing you from doing something invalid, and hiding noise from possibilities that are not meaningful) is a good practice regardless of your client.

When I see GraphQL APIs where the client is using them like a low-level ORM, it seems like it's the wrong abstraction to me. The way I think of it, GraphQL works best as a high-level API where its type system clearly expresses its API, rather than a low-level database access interface.

**Comment by Maxim-Filimonov** [comment]
Let's take github api as example:
```
{
  securityAdvisories(first: 10, orderBy: {field: PUBLISHED_AT, direction: ASC}) {
    edges {
      node {
        description
      }
    }
  }
}
```
How would you write a query using elm-graphql ? I see the same problem with optionals.

**Comment by dillonkearns** [comment]
Hey Maxim,

Sorry for the slow response, I've been busy preparing for and speaking at several different conferences the last month.

Thanks for the example. I like taking the Github API for considering the API here, because as I said my goal is for elm-graphql to work very nicely for high-level APIs, so examining low-level database access APIs (essentially using elm-graphql as an ORM), it's a bit hard for me to evaluate design decisions. So thanks, I appreciate the Github example 😄!

Would you mind building up that query (similar to your original comment) with elm-graphql syntax?

Both how you would do it in its current form, and how it might look with a new syntax. And if you don't mind, could you show the current form without any optional arguments extracted to constants? That way it might be a little easier to compare the two syntaxes side-by-side.

Thank you!

**Comment by Maxim-Filimonov** [comment]
@dillonkearns sorry for the delay with the response, was on retreat myself. Slowly coming back to life, added this to my todo for next week

**Comment by Maxim-Filimonov** [comment]
Okay. Apparently, I dropped a ball on this completely. Sorry @dillonkearns 
I have found a solution for Hasura meanwhile - https://docs.hasura.io/1.0/graphql/manual/schema/relationships/database-modelling/many-to-many.html#flattening-a-many-to-many-relationship-query
At least for many-to-many, it flattens the query a bit.

Finally, made to do the query doesn't look that bad:
```
module GithuQuery exposing (query)

import Github.Enum.OrderDirection exposing (OrderDirection(..))
import Github.Enum.SecurityAdvisoryOrderField exposing (SecurityAdvisoryOrderField(..))
import Github.InputObject exposing (buildSecurityAdvisoryOrder)
import Github.Query
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet as SelectionSet exposing (SelectionSet)


query =
    Github.Query.securityAdvisories filter SelectionSet.empty


filter : Github.Query.SecurityAdvisoriesOptionalArguments -> Github.Query.SecurityAdvisoriesOptionalArguments
filter args =
    { args | first = Present 10, orderBy = Present orderBy }


orderBy : Github.InputObject.SecurityAdvisoryOrder
orderBy =
    buildSecurityAdvisoryOrder { field = PublishedAt, direction = Asc }
```

**Comment by Maxim-Filimonov** [comment]
Raised issue with the Hasura team. Using custom functions for now as a solution to this problem.

**Comment by dillonkearns** [comment]
Hi @Maxim-Filimonov, thanks so much for looping back around to share what you learned here!
