### ISSUE TITLE
Add an option to generate code as an Elm package

### ISSUE THREAD

**Issue by Punie** [dillonkearns/elm-graphql#172]
Hi!

First of all, I absolutely LOVE this library and the code generation it provides for GraphQL endpoints.
I recently started working with Github v4 GraphQL API and it's been an absolute pleasure to have all this code generated for me. But having that huge folder (>400 files) of Github specific code in every Elm project using that API makes me a little uneasy and I wanted to try something out.

What I set out to do is extract all the generated code in its own Elm project as a package, thus providing two major benefits:
- it could now be simply imported in any application that needs interaction with the Github API
- the documentation for the generated code could be browsed with a tool like [elm-doc-preview](https://github.com/dmy/elm-doc-preview) (which is absolutely fantastic).

The main issue with that is that it is not realistic to add all the necessary missing doc comments by hand to make it compile as an elm package and produce the documentation (it's a shame that Elm makes it impossible to generate the documentation for an application type project).

What I would like to see is an option in the generator CLI to generate the code as a complete elm package instead of a simple namespaced folder holding it.

However, I realise that this might be a lot of work and I would like some feedback on whether I'm the only one who sees a benefit in such a thing or if this would be a feature many folks would like to see happen. And if that is the case, I would be more than happy to help developing that feature.

**Comment by dillonkearns** [comment]
Hello!

I'm traveling at the moment, but I'll do my best to give my initial thoughts so we can continue the discussion.

I've considered the same thing, I've actually published packages in the past for the purpose of demos so that I can publish code examples on ellie (because you can't have multiple files so it's the only way to accomplish that). The way I did it was by using the autogenerated doc comments where they existed, and manually adding it in a few places. But it becomes unsustainable quickly even for relatively small APIs.

On the other hand, I think it's worth being careful about having lots of autogenerated APIs and making the barrier to doing that too low. That could create a lot of noise and reduce the trust people have in the community packages to some extent. It seems like people have the ability to generate this code in a `gen` folder and not worry about the generated code, and they can even see the docs for the local code that contains doc comments if they have an editor that supports it. Although it's true that they wouldn't be able to look it up on a web page like the elm package site, which would be a cool feature to have for local code! I think that might be a better feature to put effort into... maybe you could contribute a fork of https://www.npmjs.com/package/elm-doc-preview that adds that functionality?

My gut feeling is that it's best not to create too many features geared towards making it easy to publish lots of packages out of GraphQL APIs. I think that it's totally reasonable to have a community maintained Github GraphQL API, but perhaps it could clean up some of the oddities (like unnecessary nullable fields and things like that)? I would look at libraries in other communities for inspiration (Ruby has a lot of DSLs for consuming APIs for example). If you're publishing an elm package, it seems to me that it's best to have that be something that a human is taking care to maintain and clean up, rather than just having something autogenerated that may have some quality issues and not be up to par with the standard we expect with elm packages. Just having a raw GraphQL API often has rough edges, so it seems like having it be fully automated could be a path to encouraging that kind of package with rough edges.

If you'd like to do something like that with the Github API, I would start by doing a proof of concept with the library as it is right now. Then list out the steps that you had to take to get it to a certain level of quality, and to add in docs in the appropriate places, etc. Then from that list, that could be a starting point for discussing what would the process look like for maintaining a package like that, and where (if anywhere) would features need to be added to elm-graphql to support that.

I'm a fan of doing the thing by hand before automating the thing. I find that it helps give a sense of what the most important work is and how to do it best. Hope that is helpful!

Best regards,

Dillon

**Comment by dillonkearns** [comment]
Hello, I'll close this issue for now, but if you'd like to continue the discussion feel free to re-open to add more thoughts. In particular, I think a good starting point would be an example of a published `elm-graphql`-based package to see how that goes in the real-world with the current state. Then we can have an example to consider how that goes and whether it's a good idea to improve that workflow and reduce the barrier to generating packages.
