### ISSUE TITLE
Question: Updated Ellie example

### ISSUE THREAD

**Issue by Wolfsun** [dillonkearns/elm-graphql#243]
Is there an updated Ellie example, the current one isn't working for me on Elm 0.19. Thanks for any help here.

**Comment by dillonkearns** [comment]
I don't have bandwidth to update it at the moment, but it would be nice to have that working. Back with Elm 0.18, I had a package published that contained the example code (since you can't have multiple source modules with Ellie). But it was hard to maintain with updates because I had to regenerate the code, update the module documentation so I could publish it, push it as an Elm package, update the Elm package in Ellie, update the link.

It's probably worth doing again now since the package has been relatively stable recently.

For now, I recommend running the examples using Elm reactor. Just do a git clone of this repository, `cd examples`, and use `elm reactor` to run the examples. Feel free to ask for help in [the #graphql channel in the elm slack](http://elmlang.herokuapp.com/).

**Comment by Wolfsun** [comment]
Thanks for the reply. I'll work my way through the examples and see how it goes.

**Comment by dillonkearns** [comment]
It might make sense to use something like codesandbox.io for the examples, actually, instead of Ellie. As nice as Ellie is, it pretty directly has a stated mission that doesn't include this use case (it just wants single module sharable Elm snippets).

With codesandbox.io, we can even set up a process to run the `elm-graphql` CLI and have it update the generated code, so people can play around with it in a nice virtual environment there. And it would be way easier to maintain.

**Comment by Wolfsun** [comment]
Makes sense, I'll look into that, perhaps I could put together an example for noobs when I'm up and running. Still struggling with the initial setup following the examples folder using the StarWars api. Using Example00SingleFieldQuery.elm I'm getting an error 

`-- MODULE NOT FOUND ---------------

You are trying to import a `DateFormat` module:

4| import DateFormat exposing (text)`

I'm not able to find a version of DateFormat for elm 0.19. I'll try and work around this for now.

**Comment by Wolfsun** [comment]
I've been able to work around the missing module but now I'm getting a similar issue to what I was getting when trying to work with my own api, I'll try asking on slack.

-- TYPE MISMATCH --------------- /home/james/Code/Elm/Swapi/src/Main.elm


Something is off with the body of the `query` definition:

36|     Query.human { id = CustomScalarCodecs.Id 1001 } StarWars.Object.Human.id
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
This `human` call produces:

    SelectionSet (Maybe StarWars.ScalarCodecs.Id) RootQuery

But the type annotation on `query` says it should be:

    SelectionSet (Maybe CustomScalarCodecs.Id) RootQuery


-- TYPE MISMATCH --------------- /home/james/Code/Elm/Swapi/src/Main.elm


The 1st argument to `human` is not what I expect:

36|     Query.human { id = CustomScalarCodecs.Id 1001 } StarWars.Object.Human.id
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
This argument is a record of type:

    { id : CustomScalarCodecs.Id }

But `human` needs the 1st argument to be:

    Query.HumanRequiredArguments

**Comment by Wolfsun** [comment]
I've resolved the above issue by setting the custom codecs flag. Think I am getting there now. Thanks
