### ISSUE TITLE
Create more complex example of mutation

### ISSUE THREAD

**Issue by jmonasterio** [dillonkearns/elm-graphql#289]
Found "simple mutation" example, but can't see how to make a mutation that takes a parameter and returns a list of objects, for example.

**Comment by dillonkearns** [comment]
Hello @jmonasterio, in GraphQL (and in elm-graphql), mutations and queries are both just composed of Selection Sets. So there is no difference in the way that you handle parameters, get back objects, lists of objects, etc. The only thing the differs between the two is how you begin building one up, but otherwise they are the same. Hope that's helpful. Feel free to contribute an example if you can think of a way to improve the docs, I'd be happy to merge in a pull request!

**Comment by Anton-4** [comment]
I am new to GraphQL and also encountered this issue. I suggest to re-open the issue, I will submit a PR soon.
