### ISSUE TITLE
TypeError: Object.entries is not a function

### ISSUE THREAD

**Issue by Ulrar** [dillonkearns/elm-graphql#308]
Hi,

I wrote a quick server using python graphene, and I'm serving it using flask-graphql on localhost:5000.
When I try to run elm-graphql to generate the code, I'm getting an error I couldn't find much about 👍 

```
$ elm-graphql http://localhost:5000 --base AWS --output src/
Fetching GraphQL schema...
Generating files...
(node:29988) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Object.entries is not a function
```

I have an admittedly unusual setup at work, I'm running all of this in cygwin if that matters, and there's a pretty aggressive proxy between me and the internet, but that shouldn't apply to localhost.

Would that be coming from my server's response, or from my local nodejs version ? It's pretty old (I think, I know nothing about node) : 

```
$ node --version
v6.9.2
$ npm --version
6.13.7
```

Hoping the node version isn't the issue, as getting that upgraded would be a huge pain :D 
thanks

**Comment by dillonkearns** [comment]
Hi @Ulrar, thanks for providing the context on node versions, that makes it easier to answer the question quickly.

Unfortunately, you will have to upgrade because the `Object.entries` function which something in the build depends on is not available in Node version 6. Here's an issue that describes that: https://github.com/rails/webpacker/issues/1021.

If you use NVM, you can set it up to use a particular Node version when you run `elm-graphql`, and then switch back for the other things which you haven't upgraded. That would be one way to manage that.

**Comment by Ulrar** [comment]
Hi,

I don't use node at all so I don't mind upgrading, the issue will be to go
through the hoops to get that done. The joys of not being an admin of your
own computer ..

Anyway thanks for the quick answer !

**Comment by dillonkearns** [comment]
Ah, yeah that should be easier at least. You might even see a performance boost from it!
