### ISSUE TITLE
Namespace maintenance

### ISSUE THREAD

**Issue by pravdomil** [dillonkearns/elm-graphql#494]
Hello, there seems to be three different ways how to name GraphQL module.
I think that it should be "GraphQl" (take example from Browser.Dom).
What do you think?

Screenshot:
<img width="276" src="https://user-images.githubusercontent.com/2387356/113850754-1439f600-979b-11eb-8273-79ee5c9cf04d.png">

**Comment by dillonkearns** [comment]
I think they are all valid options. It's actually a good thing that they have different module names because that prevents issues with namespace collisions if someone, say, were migrating between packages and had two installed at the same time (Elm doesn't currently have a way to handle that).

But either way, the spelling is going to stay as is since it would require a breaking change, and it's a matter of preference.

**Comment by pravdomil** [comment]
So I have made exception for modules starting with GraphQL and merge them together.

Now you can search for all GraphQL modules in packages browser https://elm.pravdomil.com/packages/ (group by modules and search "graph").

<img src="https://user-images.githubusercontent.com/2387356/114030090-7c133e00-987a-11eb-811d-b911ea7368e9.png" width="256">
