### ISSUE TITLE
Leverage free CI solution to automate builds for PRs

### ISSUE THREAD

**Issue by aaronwhite** [dillonkearns/elm-graphql#90]
I have experience with CircleCI which offers a free build container or more for OSS projects. This would be a convenient way to automate builds & tests as a requirement before accepting any PR

**Comment by dillonkearns** [comment]
Hey @aaronwhite! Thanks for the issue, that's nice of you to offer. Would it be different that the current Travis integration?

https://travis-ci.org/dillonkearns/elm-graphql/branches

I have it run the unit and acceptance tests, and it tells me the status on PRs, too!

**Comment by aaronwhite** [comment]
Hah! Didn’t realize- is it configured to be a required step before PRs are greenlit
by Github?

- Aaron
@aaronwhite
http://singularity.vc

Sent via Superhuman iOS ( https://sprh.mn/?vip=aaron@singularity.vc )

**Comment by dillonkearns** [comment]
Hey Aaron,

Yes, it looks like it would just be a matter of configuring it as a required check: https://help.github.com/articles/enabling-required-status-checks/

I haven't actually found the required check to be necessary since I just look at whether there's a checkmark or a red X before I merge. At times I've wanted to address some build issue myself and not make the contributor do it. So I think I'm happy with the current state of the CI & PR integration!

Thanks again for offering your help here, though! I appreciate it!
