### ISSUE TITLE
Using gql union types can result in invalid query

### ISSUE THREAD

**Issue by nonpop** [dillonkearns/elm-graphql#95]
If I have this schema:
```graphql
type Foo {
    id: Int!
}

type Bar {
    id: String!
}

union FooBar = Foo | Bar

type Query {
    fooBars: [FooBar!]!
}
```
and this graphql-elm query builder:
```elm
query =
    Api.Query.selection identity
        |> with
            (Api.Query.fooBars
                (ApiFooBar.selection
                    { onFoo = ApiFoo.selection Foo |> with ApiFoo.id
                    , onBar = ApiBar.selection Bar |> with ApiBar.id
                    }
                )
            )
```
then the generated query is
```graphql
query { fooBars { __typename ...on Foo { id } ...on Bar { id } } }
```
which is invalid according to [the spec](https://facebook.github.io/graphql/draft/#sec-Field-Selection-Merging), because the `id` fields in the fragments have non-mergeable types. When running the query against a graphql-go or graphql-js server the response is `Fields "id" conflict because they return conflicting types Int! and String!. Use different aliases on the fields to fetch both if this was intentional.`

The solution is to change the query to something like
```graphql
query { fooBars { __typename ...on Foo { fooId: id } ...on Bar { barId: id } } }
```
which works as expected.

I can provide the full elm source and an example graphql-js server if needed.

**Comment by dillonkearns** [comment]
Thank you very much for reporting the issue and providing all these details here @nonpop!

I believe that Fragment Aliases would solve this problem very well if they were added to the GraphQL spec. The proposal for that feature was closed, citing a lack of a champion. I have offered to champion the issue, please see my post here for more details: https://github.com/facebook/graphql/issues/137#issuecomment-443811960

I'm open to other ideas for solving this problem, but I can't think of one that is independent of context (i.e. a Field being added doesn't know whether it is part of a type condition fragment or not, it only knows about itself). See the post I linked to for more details. Let me know if you have any thoughts or ideas on this! In the meantime, I'll work on championing this proposal.

**Comment by dillonkearns** [comment]
@nonpop I just responded on the GraphQL Spec thread, see my update here: https://github.com/facebook/graphql/issues/137#issuecomment-444223606

In a nutshell, it would be possible to use an alias with the typename appended for each scalar field. It feels a little hacky, but it would solve the problem. I discussed in more detail in the message above.

**Comment by nonpop** [comment]
I hope they at least answer the question about the rationale of the behavior as it does feel weird. As for the elm-graphql issue itself, there's no need to hurry with a hacky solution since we modified the server to have "hard-coded aliases" in the types themselves. Of course this is also hacky but now at least we can move forward.

**Comment by dillonkearns** [comment]
Sounds good, thank you for the update @nonpop 👍 I agree, it would be nice to find a non-hacky solution, even though aliasing every scalar would solve the problem. It just seems like it shouldn't be necessary. It would be nice to get that properly solved instead of hacking around it!

**Comment by dillonkearns** [comment]
I'll keep you posted on any responses from the GraphQL team or updates from my end.

**Comment by dillonkearns** [comment]
Hello @nonpop, Ivan from the GraphQL team was very kind to give us a quick response explaining the rationale! See the discussion and my reply here: https://github.com/facebook/graphql/issues/137#issuecomment-444623011. To summarize, that was added to the spec to support some GraphQL clients which generate types based on the input GraphQL queries. These types of queries would cause them to generate invalid code.

So I think unfortunately our best option here is to use the scalar aliases as I described above.

It will add some complexity to the code generation, but not too much. The main thing I'm concerned about actually is the unnecessary noise in the generated queries. Especially when introducing this to beginners, it's nice to avoid the noise. I'm thinking maybe I can use a helper function that removes all aliases from the demos in the `examples` folder at least so that they're easier to follow. That may result in those queries being invalid, but I don't think they need to be run so it should be good enough 🤔

**Comment by nonpop** [comment]
Thanks for the updates! I'll return with the details in a few hours but for now some quick points:
 - I don't think I've ever seen a server return other than 200, except when a resolver crashes and it gives 500
 - Either I'm misunderstanding something or Absinthe should give an error. However, a recent comment in Elm slack's #graphql channel suggests that Absinthe also handles null propagation incorrectly (as does graphql-go btw)
 - Can you try modifying your example server so that it returns an array of different types heros, see if that makes a difference?

**Comment by nonpop** [comment]
Ok, so here is a graphql-js example server:
```javascript
var express = require('express');
var graphqlHTTP = require('express-graphql');
var { buildSchema } = require('graphql');

var schema = buildSchema(`
type Foo {
    id: Int!
}

type Bar {
    id: String!
}

union FooBar = Foo | Bar

type Query {
    fooBars: [FooBar!]!
}
`);

var root = {
    fooBars: () => {
        return [
            {
                __typename: 'Foo',
                id: 42
            },
            {
                __typename: 'Bar',
                id: "hello"
            },
        ];
    },
};

var app = express();
app.use('/graphql', graphqlHTTP({
    schema: schema,
    rootValue: root,
    graphiql: true,
}));
app.listen(4000);
console.log('Running a GraphQL API server at localhost:4000/graphql');
```
package.json:
```json
{
  "dependencies": {
    "express": "^4.16.4",
    "express-graphql": "^0.7.1",
    "graphql": "^14.0.2",
    "node": "^11.3.0"
  }
}
```
Run this and you get GraphiQL at `localhost:4000/graphql`. If you enter the following query:
```graphql
query {
  fooBars {
    __typename
    ...on Foo {
      id
    }
    ...on Bar {
      id
    }
  }
}
```
then the server responds with a `400 Bad Request` (so I remembered wrong in the previous comment), and the response body is:
```json
{
  "errors": [
    {
      "message": "Fields \"id\" conflict because they return conflicting types Int! and String!. Use different aliases on the fields to fetch both if this was intentional.",
      "locations": [ { "line": 5, "column": 7 }, { "line": 8, "column": 7 } ]
    }
  ]
}
```
There is not even a null `data` field, which indicates that the error happened during validation, before the execution phase.

**Comment by nonpop** [comment]
Also note that in both my example and your example GraphiQL actually underlines the first `id`/`name` field and hovering shows an error.

**Comment by dillonkearns** [comment]
Thank you for the details on this @nonpop! That's very helpful to see exactly what response you're getting. So it seems like maybe if you're executing the queries using Graphiql, it will sometimes skip the validations (that's written in the spec that if it knows it's run the validations the server doesn't need to re-run them).

Also, I wanted to clarify this point:

> * Either I'm misunderstanding something or Absinthe should give an error. However, a recent comment in Elm slack's #graphql channel suggests that Absinthe also handles null propagation incorrectly (as does graphql-go btw)

That's actually not accurate that it was an error. I clarified that incorrect statement in the slack discussion:

> For example Absinthe will return `null` but also annotate that with the error.

> I would consider that an error, though (and so would `dillonkearns/elm-graphql`). And that is not an incorrect implementation, that's a valid response (the data returned doesn't have to match the schema if it's returned next to an error). http://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability

**Comment by dillonkearns** [comment]
@nonpop so I've got an implementation working that fixes the issue on this thread. You can [run the query that's now being generated](https://elm-graphql-normalize.herokuapp.com/?query=query%20%7B%0A%20%20conflictingTypesUnion%20%7B%0A%20%20%20%20__typename0%3A%20__typename%0A%20%20%20%20...on%20Dog%20%7B%0A%20%20%20%20%20%20id2095588262%3A%20id%0A%20%20%20%20%7D%0A%20%20%20%20...on%20Cat%20%7B%0A%20%20%20%20%20%20id2593563956%3A%20id%0A%20%20%20%20%7D%0A%20%20%20%20...on%20MaybeId%20%7B%0A%20%20%20%20%20%20id2705767912%3A%20id%0A%20%20%20%20%7D%0A%20%20%20%20...on%20ListId%20%7B%0A%20%20%20%20%20%20id1373293297%3A%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A). This is running on a server I have for checking odd corner cases!

I added a simple regex that strips all the aliases in the demo code so that beginners won't be confused when they see all the noise. It can result in invalid queries, I'm thinking it might make sense to include a button to toggle the Regex.replace in the UI for the demos in the `examples` folder.

So anyway, as you can see, the generated queries now differ because they have differing types (you can see all the validation errors if you strip off the aliases). What it's doing now is concatenating the arguments of a field and the type of the field, and hashing that into a number to get an alias.

What do you think? I think it's ready to ship unless you have any other thoughts. Thanks again for your help on this!

**Comment by nonpop** [comment]
Thanks for fixing this so quickly! The queries are indeed quite noisy, which makes it harder to read them in the rare cases you have to. But having to hack the server is certainly worse, so go ahead and ship. I think it's better to have something correct and ugly than broken and clean. You can always refine the implementation details later if new ideas come up.

As for a couple other not-really-relevant-to-this-issue points:
 - Absinthe should not skip validation if running via graphiql since even though graphiql *checks* the queries and shows errors, it will still also send invalid queries to the server, and the server should not execute invalid queries.  I think the only cases where the server can skip validation is if it recognizes the query as a pre-checked one by some method like a whitelist or a cache or something. I actually guess that Absinthe does not skip validation but instead it just has an incomplete set of validations.
 - Absinthe/graphql-go returning nulls for non-nullable fields is also not ok. From the spec you quoted: 

    > Since Non-Null type fields cannot be null, field errors are propagated to be handled by the parent field. If the parent field may be null then it resolves to null, otherwise if it is a Non-Null type, the field error is further propagated to it’s parent field.

**Comment by dillonkearns** [comment]
> * Absinthe should not skip validation if running via graphiql since even though graphiql _checks_ the queries and shows errors, it will still also send invalid queries to the server, and the server should not execute invalid queries.  I think the only cases where the server can skip validation is if it recognizes the query as a pre-checked one by some method like a whitelist or a cache or something. I actually guess that Absinthe does not skip validation but instead it just has an incomplete set of validations.

I agree that it's confusing, but the GraphQL spec does allow for validations to be skipped to allow for certain queries to be backwards compatible. I was actually getting a 200 when I ran that query against my Absinthe server directly as well, so I'm guessing that's the reason for the discrepancy between your server framework and Absinthe 🤷‍♂️ 

See https://facebook.github.io/graphql/June2018/#sec-Validation

> As GraphQL type system schema evolve over time by adding new types and new fields, it is possible that a request which was previously valid could later become invalid. Any change that can cause a previously valid request to become invalid is considered a breaking change. GraphQL services and schema maintainers are encouraged to avoid breaking changes, however in order to be more resilient to these breaking changes, sophisticated GraphQL systems may still allow for the execution of requests which at some point were known to be free of any validation errors, and have not changed since.

> * Absinthe/graphql-go returning nulls for non-nullable fields is also not ok. From the spec you quoted [...]

That's actually not accurate. If the GraphQL response contains `errors` associated with a given field, then the data for that field can be null (even if that field is non-nullable). Take a look at https://facebook.github.io/graphql/October2016/#sec-Errors-and-Non-Nullability.

**Comment by dillonkearns** [comment]
> You can always refine the implementation details later if new ideas come up.

I agree, and really the only reasons that the raw queries matter at all are:
1) Debugging
2) Learning & demos (seeing the generated queries based on Elm code)

I think that for 1), it's totally fine to have some extra aliases in there. 2) is the only thing I'm concerned about, and I think that a checkbox to toggle stripping aliases and a little link to an FAQ section would be sufficient for that. Thanks for all your feedback!

The release will need to be a major update to the Elm package unfortunately because some internal modules are exposed for the generated code to consume. And one of those functions now takes a new parameter. But no biggie, I'll ship it today 👍

**Comment by dillonkearns** [comment]
@nonpop I just pushed out Elm package version 3.0.0 and NPM version 3.0.1. I think this is in good shape now! Would you mind confirming that this is resolved for you and closing this issue out if so? Thank you! 😄

**Comment by nonpop** [comment]
Works, thank you!

**Comment by dillonkearns** [comment]
Great! Thanks for confirming 👍
