### ISSUE TITLE
String to Enum

### ISSUE THREAD

**Issue by sporto** [dillonkearns/elm-graphql#98]
For enums, it would be nice to generate a function like:

`String -> Result String Enum`

When working with Enums, sometimes we need to convert string back to union types.

E.g. you create a dropdown with options of each Enum. The dropdown uses `onInput` which emits a `Change String` message.

It is possible to use the generated `decoder` like:

```
type Thing
    = A
    | B


decoder : Decoder Thing
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "A" ->
                        Decode.succeed A

                    "B" ->
                        Decode.succeed B
    
                    _ ->
                        Decode.fail (...)
            )
````

```
result =
    Decode.decodeString Thing.decoder "\"A\""
```

But it would be nicer to have something like:

```
result =
    Thing.fromString "A"  ----> Ok A
```

The decoder could use this internally

Thanks

**Comment by dillonkearns** [comment]
Hey @sporto, seems like a good idea!

Would you mind copying the code from this file and modifying with the possible changes you're describing? https://github.com/dillonkearns/elm-graphql/blob/master/examples/src/Swapi/Enum/Episode.elm

That would make it a little easier for me to understand what would address the needs for your use case. And then I can use that as a code gen target for when I'm editing the template.

Ideally you would base the changes on some real-world code that you have. 

For example, I imagine that you would need to have `Episode.toString` as well for this to work, right? Because if you're making a <select> then you would need to serialize the enum values as well as deserialize them.

Thank you!

**Comment by sporto** [comment]
Sure:

```
-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Swapi.Enum.Episode exposing (Episode(..), decoder, fromString, list, toString)

import Json.Decode as Decode exposing (Decoder)


{-| One of the films in the Star Wars Trilogy

  - Empire - Released in 1980.
  - Jedi - Released in 1983.
  - Newhope - Released in 1977.

-}
type Episode
    = Empire
    | Jedi
    | Newhope


list : List Episode
list =
    [ Empire, Jedi, Newhope ]


decoder : Decoder Episode
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case fromString string of
                    Ok enum ->
                        Decode.succeed enum

                    Err err ->
                        Decode.fail err
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : Episode -> String
toString enum =
    case enum of
        Empire ->
            "EMPIRE"

        Jedi ->
            "JEDI"

        Newhope ->
            "NEWHOPE"


fromString : String -> Result String Episode
fromString string =
    case string of
        "EMPIRE" ->
            Ok Empire

        "JEDI" ->
            Ok Jedi

        "NEWHOPE" ->
            Ok Newhope

        _ ->
            Err ("Invalid Episode type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
```

**Comment by ssbb** [comment]
Interesting, I am doing the same myself since widely use Enums from GraphQL-generated code in my application  - for things like filtering (show me only projects with status "New", etc.).

Personally I am use `enumNameToString` for things like querystring encoding (decoding is done with provided `decode` function) and mapping values when working with `Html.select`.

**Comment by dillonkearns** [comment]
@sporto thanks for providing the code! That looks perfect, I'll use that as the code generation target 👍

**Comment by sporto** [comment]
@dillonkearns seems that https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-NPM-PACKAGE.md#330---2018-03-31 cover this? Maybe result might have been better as you can get the error?

**Comment by sporto** [comment]
This is done, closing

**Comment by dillonkearns** [comment]
For reference in case anybody looks at this thread looking for advice, Ilias shared a nice code snippet for turning it into an `Err`:

```elm
input 
  |> YourEnum.fromString
  |> Result.fromMaybe (input ++ " passed as query param is not a valid `YourEnum`.")
```
